name: Scala CI

on:
  push:
    branches:
      - master
      - 'release/**'
      - 'hotfix/**'
      - '!feature/**'
      - '!refactoring/**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run assembly
        run: sbt clean assembly

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Configure sysctl limits
        run: |
          # sudo swapoff -a
          # sudo sysctl -w wm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Run Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.9.0

      - name: Check Elasticsearch
        run: curl -sS -XGET localhost:9200

      - name: Set env
        run: echo ::set-env name=CI_BRANCH::$(git rev-parse --abbrev-ref HEAD)

      - name: Run tests with coverage
        env:
          gw_user_id: 'occidere'
          gw_es_endpoint: 'localhost:9200'
          gw_tasks: 'followerWatchTask,repositoryWatchTask,reactionWatchTask'
          gw_line_bot_id: ${{ secrets.GW_LINE_BOT_ID }}
          gw_line_channel_token: ${{ secrets.GW_LINE_CHANNEL_TOKEN }}
          gw_github_api_token: ${{ secrets.GW_GITHUB_API_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: sbt coverage test coverageReport coveralls

#      Temporarily ignore because Coveralls Github Action only support lcov file not covertura.xml
#      Check: https://github.com/scoverage/sbt-coveralls/issues/126
#      - name: Coveralls GitHub Action
#        uses: coverallsapp/github-action@v1.1.2
#        with:
#          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
#          parallel: true

#  finish:
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Coveralls Finished
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
#          parallel-finished: true